Repository MicrosoftDocs/azure-docs.sv-se, pull requests merged in 2019-07, with the labels that each got.

#359 Fix mistranslation
  articles/azure-monitor/platform/autoscale-webhook-email.md
Labels: Accepted

#360 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#362 Fix mistranslation
  articles/blockchain/service/send-transaction.md
Labels: Accepted

#361 Fix mistranslation
  articles/blockchain/service/manage-consortium-powershell.md
Labels: Accepted

#363 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#364 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted, Linguistic Suggestion

#366 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, Linguistic Suggestion

#365 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, Linguistic Suggestion

#367 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted

#368 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted

#369 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#371 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-customize-cluster-linux.md
Labels: Accepted

#370 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted

#372 Fix mistranslation
  articles/mariadb/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#374 Fix mistranslation
  articles/mysql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#373 Fix mistranslation
  articles/mariadb/tutorial-design-database-cli.md
Labels: Accepted, Linguistic Suggestion

#376 Fix mistranslation
  articles/postgresql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#375 Fix mistranslation
  articles/mysql/tutorial-design-database-using-cli.md
Labels: Accepted, Linguistic Suggestion

#377 Fix mistranslation
  articles/postgresql/tutorial-design-database-using-azure-cli.md
Labels: Accepted, Linguistic Suggestion

#378 Fix mistranslation
  articles/traffic-manager/traffic-manager-powershell-arm.md
Labels: Accepted

#379 Fix mistranslation
  articles/app-service-mobile/app-service-mobile-ios-get-started-offline-data.md
Labels: Accepted

#381 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, Linguistic Suggestion

#380 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#383 Fix mistranslation
  articles/service-bus-messaging/service-bus-amqp-protocol-guide.md
Labels: Accepted

#384 Fix mistranslation
  articles/storage/common/storage-powershell-independent-clouds.md
Labels: Accepted, Linguistic Suggestion

#385 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted

#386 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted

#382 Do not translate "VS Code"
  articles/aks/TOC.yml
  articles/cosmos-db/create-mongodb-flask.md
  articles/dev-spaces/get-started-nodejs.md
  articles/dev-spaces/toc.yml
  articles/iot-edge/tutorial-machine-learning-edge-03-generate-data.md
  articles/iot-edge/tutorial-python-module.md
  articles/logic-apps/quickstart-create-logic-apps-visual-studio-code.md
  articles/sql-database/sql-database-connect-query-vscode.md
  articles/sql-database/toc.yml
  includes/iot-hub-get-started-device-selector.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#387 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#388 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#389 Fix mistranslation
  articles/azure-resource-manager/resource-group-authoring-templates.md
Labels: Accepted

#391 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-string.md
Labels: Accepted

#390 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: Accepted

#392 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#393 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#394 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted

#395 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted

#396 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted, Linguistic Suggestion

#397 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Linguistic Suggestion

#398 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted

#399 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted

#400 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, Linguistic Suggestion

#401 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted

#402 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted
